### ISSUE TITLE
objectives: To meet your #5 Interactive Dashboards - view candidate progress, job seekers’ postings, and track recruitment performance - job seeker dashboard

### ISSUE THREAD

**Issue by thirdygayares** [Jobboardplatform-svfc/JobBoardPlatform_Documentation#12]
add two tables in ERD and data dictionary

`1. Job_Performance Table`

| Field Name          | Data Type   | Description                                                     |
|---------------------|-------------|-----------------------------------------------------------------|
| performance_id       | INT         | Primary key, unique identifier for each performance record.      |
| job_id               | INT         | Foreign key to the `Job_Posting` table.                         |
| applications_count   | INT         | Number of applications submitted for the job posting.           |
| views_count          | INT         | Number of times the job post was viewed by candidates.          |
| open_date            | DATETIME    | Date when the job posting became active.                        |
| close_date           | DATETIME    | Date when the job posting was closed or filled.                 |
| time_to_fill         | INT         | Number of days the job post remained open before being filled.   |
| updated_at           | DATETIME    | Date when this performance record was last updated.             |

`2. Job_Interaction Table`

| Field Name          | Data Type   | Description                                                     |
|---------------------|-------------|-----------------------------------------------------------------|
| interaction_id       | INT         | Primary key, a unique identifier for each interaction record.      |
| user_id              | INT         | Foreign key to the `User` table (tracks which user interacted).  |
| job_id               | INT         | Foreign key to the `Job_Posting` table (which job was interacted with). |
| interaction_type     | ENUM        | Type of interaction (`VIEW`, `APPLY`).                  |
| interaction_date     | DATETIME    | Date and time when the interaction occurred.                    |
| is_applied           | BOOLEAN     | Flag to check if the user has applied to the job.               |

Job_Posting ↔ Job_Performance (One-to-One)
Job_Posting ↔ Job_Interaction (One-to-Many)
User ↔ Job_Interaction (One-to-Many)

**Comment by rodney-lqr** [comment]
Done po sir
